CONFIG_WIFI_ESP32=y
CONFIG_NEUROLINK_NODE_ID="unit-01"
CONFIG_NEUROLINK_ZENOH_MODE="client"
CONFIG_NEUROLINK_ZENOH_CONNECT="tcp/192.168.2.95:7447"
CONFIG_NEUROLINK_ZENOH_PICO_DEBUG=y
CONFIG_NEUROLINK_ZENOH_PICO_DEBUG_LEVEL=3