CONFIG_NEUROLINK_APP_PREFER_EXTERNAL_ELF_BUFFER=n
CONFIG_NEUROLINK_APP_PREFER_PSRAM_ELF_BUFFER=n
CONFIG_NEUROLINK_APP_STATIC_ELF_BUFFER_SIZE=28672
CONFIG_NEUROLINK_APP_MAX_LOADED=1
CONFIG_NEUROLINK_APP_MAX_RUNNING=1
CONFIG_LLEXT_HEAP_SIZE=32
CONFIG_NEUROLINK_APP_REJECT_STAGING_TEXT_EXEC=y
CONFIG_NEUROLINK_APP_FIXUP_STAGING_TEXT_ALIAS=y
CONFIG_LLEXT_EXPORT_DEVICES=y
CONFIG_LLEXT_EXPORT_SYMBOL_GROUP_DEVICE=y